### ISSUE TITLE
run manager.py report error

### ISSUE THREAD

**Issue by songliqiang520** [testdevhome/Autotestplat#11]
Traceback (most recent call last):
  File "/Users/mac/Desktop/Autotestplat/manage.py", line 21, in <module>
    main()
  File "/Users/mac/Desktop/Autotestplat/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/mac/Desktop/Autotestplat/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/mac/Desktop/Autotestplat/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/Users/mac/Desktop/Autotestplat/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/mac/Desktop/Autotestplat/venv/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/mac/Desktop/Autotestplat/venv/lib/python3.6/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mac/Desktop/Autotestplat/venv/lib/python3.6/site-packages/djcelery/models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
ModuleNotFoundError: No module named 'celery.utils.timeutils'

**Comment by songliqiang520** [comment]
该安装的都安装的，还是报错，求大佬帮忙，微信也加你了

**Comment by testdevhome** [comment]
你好，目前部署环境是windows，在mac和linux上还没部署过不确定是否可行，建议在windows部署！
